### ISSUE TITLE
MrAdvice doesn't weave 

### ISSUE THREAD

**Issue by shivamtripathi** [ArxOne/MrAdvice#92] opened 2017-02-01 11:06 UTC
Though I tried to reproduce this issue in a sample application but it works fine there. However in my actual application it shows following error during build -
**MrAdvice.targets(10,5): warning : IAdvice interface not found here (not referenced means not used), exiting**

I've created few advices in a separate assembly and I am using that assembly into a Web API project. 
I've applied one of the advice on top of a class in Web API Project. So it should ideally find that as a reference to IAdvice and weave the assembly during build. It doesn't do that. But as soon as I put a dummy advice in that project, it weaves it perfectly. 

Can you help me to figure out if I am missing something? As per the documentation we don't need to do anything else apart from creating advices as an attribute and use. 

Thanks

**Comment by picrap** [comment] 2017-02-01 12:31
First thing to check: your main project should reference MrAdvice too.
Also, I didn't test at all with Web API projects, so you probably need to make some tests: what if the advice is in the project itself instead of being in a separate assembly?
I hope this helps.

**Comment by shivamtripathi** [comment] 2017-02-01 12:41
Thanks for your quick reply. Yes the main project does reference MrAdvice. If the advice is in the main project itself then it works perfectly fine but if it is in a separate assembly then it does't work (Unless I add a dummy advice in the main project too).

I tried to reproduce it in a separate application but no luck.

**Comment by picrap** [comment] 2017-02-01 18:28
This makes sense, unfortunately. I keep this issue opened and see if something can be done for it.

**Comment by picrap** [comment] 2017-03-10 21:16
I made a total blind change, because I couldn't reproduce the problem.
Can you test with version 2.4.7?

**Comment by picrap** [comment] 2017-08-05 21:52
No one here. Closing.

**Closed by picrap** 2017-08-05 21:52 UTC
Labels: bug
