### ISSUE TITLE
Error in building project 

### ISSUE THREAD

**Issue by Kahbazi** [ArxOne/MrAdvice#86] opened 2016-12-14 11:14 UTC
Hi, I get this error during build. what should I do?

```
packages\MrAdvice.2.4.3\build\MrAdvice.targets(10,5): error : Internal error during Types import: System.NullReferenceException: Object reference not set to an instance of an object.
packages\MrAdvice.2.4.3\build\MrAdvice.targets(10,5): error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateWeavingContext(ModuleDefMD moduleDefinition)
packages\MrAdvice.2.4.3\build\MrAdvice.targets(10,5): error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.Weave(ModuleDefMD moduleDefinition)
packages\MrAdvice.2.4.3\build\MrAdvice.targets(10,5): error : Please complain, whine, cry, yell at https://github.com/ArxOne/MrAdvice/issues/new

```

**Comment by picrap** [comment] 2016-12-14 14:21
First thing to do is to tell me more 😉 
Does this always happen? If not, when does this happen? A specific project? A new version of Mr. Advice? The ideal is that you provide a sample, but I know, this is often tricky.

**Comment by Kahbazi** [comment] 2016-12-15 06:24
I write an abstract class for method boundary Advice 

```
public abstract class BaseAdviceAttribute : Attribute, IMethodAsyncAdvice
{
    public async Task Advise(MethodAsyncAdviceContext context)
    {
        await OnEntry(context);
        try
        {
            await context.ProceedAsync();
            await OnSuccess(context);
        }
        catch
        {
            await OnException(context);
            throw;
        }
        finally
        {
            await OnExit(context);
        }
    }

    public  abstract Task OnEntry(MethodAsyncAdviceContext context);
    public  abstract Task OnException(MethodAsyncAdviceContext context);
    public  abstract Task OnSuccess(MethodAsyncAdviceContext context);
    public  abstract Task OnExit(MethodAsyncAdviceContext context);
}
```

and write another class that inherits from base class

```
public class LogAdviceAttribute : BaseAdviceAttribute
{
    public  override Task OnEntry(MethodAsyncAdviceContext context)
   {

   }

    public  override Task OnException(MethodAsyncAdviceContext context)
    {

    }

    public  override Task OnSuccess(MethodAsyncAdviceContext context)
    {

    }

    public  override Task OnExit(MethodAsyncAdviceContext context)
    {

    }
}
```
Theses classes are in different projects.

This is when error occurs!

**Comment by picrap** [comment] 2016-12-16 23:16
Thanks, I'll work on it in the next few days.

**Comment by picrap** [comment] 2016-12-18 11:22
Based on error, this is unrelated to advices location, unfortunately (and of course, I tried to reproduce it without any success).
Could you give more details about your project, or event better, provide a small failing sample? Sorry for inconvenience, but I'm stuck.

**Comment by dnaren** [comment] 2016-12-22 00:54
Not sure if this helps. 

This issue seems to be occurring randomly, I just created a new class library project, .Net v4.0 in VS 2015 update 3 and installed the latest nuget package v2.4.3 and the errors show up in Error List (screenshot below). 

However, the errors were gone when closed & opened VS again. 

![image](https://cloud.githubusercontent.com/assets/4179970/21411333/5aa3befe-c7ad-11e6-9ea8-6d899ff034cb.png)

**Comment by picrap** [comment] 2016-12-22 07:25
@dnaren an output window from build would be much better 👍

**Comment by picrap** [comment] 2017-03-10 21:19
Any news here? 
* @dnaren could you send me a textual output?
* @Kahbazi I've made some changes in 2.4.7. Does this help? Otherwise can you provide a sample?

**Comment by picrap** [comment] 2017-08-05 21:53
Everyone abducted by aliens. Closing.

**Closed by picrap** 2017-08-05 21:53 UTC
Labels: bug, on hold
