### ISSUE TITLE
Generic method in generic class issue

### ISSUE THREAD

**Issue by AlexanderButs** [ArxOne/MrAdvice#73] opened 2016-10-17 17:25 UTC
Use MrAdvice with dnlib (MrAdvice nuget package).
Have some issue with generic method on mono only. Can't it reproduce on windows and can't create synthetic test for this issue on linux unfortunately. Got exception only on live project.
Have async generic method in generic class like:
class Class < T1 > { async Task < IEnumerable < T2 > > Method < T2 > () }

When call this method with second parameter type got exception:

```
Error: [2016-10-17T19:36:29.858+03] 2 399 - System.AggregateException: One or more errors occurred ---> System.InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper castclass) object:__castclass_with_cache (object,intptr,intptr)
  at ArxOne.MrAdvice.Threading.TaskCompletionSourceImplementation`1[System.Collections.Generic.IEnumerable`1[System.String]].SetResult (System.Object result) [0x00000] in <filename unknown>:0 
  at ArxOne.MrAdvice.Invocation.ContinueTask (System.Threading.Tasks.Task adviceTask, ArxOne.MrAdvice.Threading.TaskCompletionSource adviceTaskSource, ArxOne.MrAdvice.Advice.AdviceValues adviceValues) [0x00000] in <filename unknown>:0 
  at ArxOne.MrAdvice.Invocation+<>c__DisplayClass1_0.<ProceedAdvice>b__1 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.TaskActionInvoker+ActionTaskInvoke.Invoke (System.Threading.Tasks.Task owner, System.Object state, System.Threading.Tasks.Task context) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ThreadStart () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
 --> (Inner exception 0) System.InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper castclass) object:__castclass_with_cache (object,intptr,intptr)
  at ArxOne.MrAdvice.Threading.TaskCompletionSourceImplementation`1[System.Collections.Generic.IEnumerable`1[System.String]].SetResult (System.Object result) [0x00000] in <filename unknown>:0 
  at ArxOne.MrAdvice.Invocation.ContinueTask (System.Threading.Tasks.Task adviceTask, ArxOne.MrAdvice.Threading.TaskCompletionSource adviceTaskSource, ArxOne.MrAdvice.Advice.AdviceValues adviceValues) [0x00000] in <filename unknown>:0 
  at ArxOne.MrAdvice.Invocation+<>c__DisplayClass1_0.<ProceedAdvice>b__1 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.TaskActionInvoker+ActionTaskInvoke.Invoke (System.Threading.Tasks.Task owner, System.Object state, System.Threading.Tasks.Task context) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ThreadStart () [0x00000] in <filename unknown>:0 
```

I have two specific methods and crashes only second one (think JIT is in business). I.e first call Method<string> is ok, and then Method<DateTime> crashes. Then restart the application and call Method<DateTime> first, and then Method<string> crashes. So it depends which method I invoke first.

**Comment by picrap** [comment] 2016-10-17 17:36
Try with build 2.0.15, and give me the output (the original type that was tried to be cast as `IEnumerable<string>`).

**Comment by picrap** [comment] 2016-10-17 17:43
Also, is is possible that the task is canceled? Because Mr. Advice does not handle canceled tasks properly (which I fixed just now)

**Comment by AlexanderButs** [comment] 2016-10-17 18:31
I think no, this task is not canceled. I comment the advice around this method and everything works ok. 
Will check new version tomorrow morning and provide you necessary info. 
Thanks for quick reply.

**Comment by AlexanderButs** [comment] 2016-10-18 07:54
Now, I have another exception related to my project context but issue I think is the same.
I'll try to explain: 
Inside this generic method I have another generic call (db call with deserialization process). When I got exception underlying library told me it can't cast i.e. 'string' value to 'DateTime' (first call was with string generic param).
It behaves like it caches first type of call and uses it for every next call even with another generic param type.

My method:
async Task<IEnumerable<T>> Method<T>()
{
return await db.GetData<T>(); // it returns type data from db
}

first call Method<string>() is ok
second call Method<DateTime>() failed with cast exception in db library. It calls db.GetData<string> inside.

Hope this is understandable.

**Comment by picrap** [comment] 2016-10-18 07:57
This may help... I'll let you know.

**Comment by AlexanderButs** [comment] 2016-10-18 08:05
Want to add.
It calls Method() with proper generic param type (this comes from exception), but call underlying generic method with incorrect generic param type.

Hope my English is not so bad ;-)

**Comment by picrap** [comment] 2016-10-18 08:06
Your english seems as good as mine... I'll let you judge of it :)
Regarding parameters, am I right if I say that the only mismatch is the result value?

**Comment by AlexanderButs** [comment] 2016-10-18 08:10
Didn't get what do you mean, honestly.
Second call looks like:
async Task < IEnumerable < DateTime > > Method<DateTime>(...)
{
return await db.GetData < string > (...); // it throws inside, because stored procedure returns DateTime
}

**Comment by picrap** [comment] 2016-10-18 08:12
What I meant is that the exception is thrown from a method named `SetResult`, right?

**Comment by AlexanderButs** [comment] 2016-10-18 08:20
Nope, it is thrown now inside db library when it tries to deserialize data it got from db.

**Comment by AlexanderButs** [comment] 2016-10-18 08:24
Last several lines of exception:

Error: [2016-10-18T10:40:05.741+03] 95 399 - MasterServer.Core.Database.Couchbase.Exceptions.ViewRequestException: Error converting value "kielxtest074_64292" to type 'DedicatedPoolServer.Repositories.BoxStatsEntity'. Path 'rows[0].value', line 2, position 80.
  at MasterServer.Core.Database.Couchbase.Repository`1+<SelectAsync>c__async6`1[DedicatedPoolServer.Repositories.DedicatedEntity,DedicatedPoolServer.Repositories.BoxStatsEntity].MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0 
  at MasterServer.Core.Services.Metrics.Aspects.MetricsAsyncAttribute+<AdviseImpl>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0 
  at MasterServer.Core.Services.Metrics.Aspects.MetricAttribute+<Advise>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <filename unknown>:0 
  at DedicatedPoolServer.Repositories.CouchbaseDedicatedRepository+<GetAllAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <filename unknown>:0 
  at DedicatedPoolServer.Services.LoadBalancerService+<GetAllDedicatedAsync>c__async2.MoveNext () [0x00000] in <filename unknown>:0 

Hope I didn't reveal any inside info.

**Comment by AlexanderButs** [comment] 2016-10-18 09:34
My method:

[MetricsAsync("app_view_request")]
protected async Task < IEnumerable < T > > SelectAsync < T > (IViewQuery query)
{
	var results = await m_bucket.QueryAsync < T > (query);
	if (!results.Success)
	{
		var message = results.Error;
		throw new ViewRequestException(message, results.StatusCode);
	}

	return results.Values;
}

**Comment by picrap** [comment] 2016-10-18 09:34
I think I found the bug, and you are right: it appears that advices to a generic method are considered to be the same, regardless generic arguments. I'll try to fix it today.

**Comment by picrap** [comment] 2016-10-18 09:39
Well, that's not the case, and the code seems correct... Still investigating...

**Comment by AlexanderButs** [comment] 2016-10-18 09:40
Just want to provide all necessary info to fix this issue.

**Comment by picrap** [comment] 2016-10-18 12:13
I have released a 2.0.17 where async advice implementation was changed (to something better, I think). However I don't know if it will solve your problem, so let me know.

**Comment by AlexanderButs** [comment] 2016-10-18 13:12
I tried it. You've broken exception handling.

**Comment by picrap** [comment] 2016-10-18 13:13
Exception handling in aspect? And otherwise, do you still get the cast error?

**Comment by AlexanderButs** [comment] 2016-10-18 13:27
If async method throws exception then client of this method gets incorrect one:

Expected: <MasterServer.Core.Database.Couchbase.Exceptions.QueryRequestException>
  But was:  <System.Reflection.TargetInvocationException> (Exception has been thrown by the target of an invocation.)
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at ArxOne.MrAdvice.Threading.TaskExtensions.GetResult (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at ArxOne.MrAdvice.Invocation+<>c__DisplayClass1_0.<ProceedAdvice>b__1 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at ArxOne.MrAdvice.Threading.TaskContinuer`1+<>c__DisplayClass0_0`1[System.Collections.Generic.IEnumerable`1[MasterServer.Core.Database.Couchbase.Test.RepositoryTest+MyEntity],System.Threading.Tasks.Task].<ContinueWith>b__0 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.TaskActionInvoker+FuncTaskInvoke`1[System.Collections.Generic.IEnumerable`1[MasterServer.Core.Database.Couchbase.Test.RepositoryTest+MyEntity]].Invoke (System.Threading.Tasks.Task owner, System.Object state, System.Threading.Tasks.Task context) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.<ThreadStart>m__1 (System.Object l) [0x00000] in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ThreadStart () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.Collections.Generic.IEnumerable`1[MasterServer.Core.Database.Couchbase.Test.RepositoryTest+MyEntity]].GetResult () [0x00000] in <filename unknown>:0 
  at MasterServer.Core.Database.Couchbase.Test.RepositoryTest+<ShouldThrowIfNotSuccessWhenSelectWithNiql>c__asyncC+<ShouldThrowIfNotSuccessWhenSelectWithNiql>c__AnonStorey1F+<ShouldThrowIfNotSuccessWhenSelectWithNiql>c__async1E.MoveNext () [0x00000] in <filename unknown>:0 

I couldn't check the original issue because CI build failed due to failed unit tests =)
I decided to not use MrAdvice in situation with generic method because of lack release time (but I use it in all other places). Will be ready to check this again in a few days (maybe earlier).

**Comment by picrap** [comment] 2016-10-18 13:40
We need to share our tests: mine worked...

**Comment by AlexanderButs** [comment] 2016-10-18 15:31
You use reflection to get task result here 
https://github.com/ArxOne/MrAdvice/blob/c3e4dfd57ae0a11d9034981caa3910f0124e2849/MrAdvice/Threading/TaskExtensions.cs#L50

If this task property throws then original exception is wrapped into TargetInvocationException. You can read this here https://msdn.microsoft.com/en-us/library/b05d59ty(v=vs.110).aspx

Original issue will check in next few days.

**Comment by picrap** [comment] 2016-10-18 15:37
Thanks, I made a blind fix (version 2.0.20), however if you have a test (or at least a few hints) to demonstrate this, it's welcome.

**Comment by AlexanderButs** [comment] 2016-10-18 15:49
Your change fixes main part of the exception issue, but by doing this
throw e.InnerException;
you erase original stacktrace information. It is overridden with new one where you rethrow this exception and original place of exception is lost.

**Comment by picrap** [comment] 2016-10-18 15:51
Yes. I'll do something better if you tell me everything else is working 😄

**Comment by AlexanderButs** [comment] 2016-10-18 15:53
How to preserve exception stacktrace you can read here
http://stackoverflow.com/questions/57383/in-c-how-can-i-rethrow-innerexception-without-losing-stack-trace

**Comment by AlexanderButs** [comment] 2016-10-18 15:57
Still not working (with 2.0.20). Now it is wrapped in AggregateException.

**Comment by picrap** [comment] 2016-10-19 07:17
Please provide me a test method on which I can work.

**Comment by AlexanderButs** [comment] 2016-10-19 07:48
Aspect:
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
public class LogSuccessAsyncAttribute : Attribute, IMethodAsyncAdvice
{
	public async Task Advise(MethodAsyncAdviceContext context)
	{
		await context.ProceedAsync();
		Console.WriteLine("Success!");
	}
}

Class:
public class Class
{
	[LogSuccessAsync]
	public async Task < int > Method()
	{
		await Task.Yield();
		throw new NullReferenceException();
	}
}

Test:
[TestFixture]
public class Tests
{
	[Test]
	public async Task ShouldTest()
	{
		await Task.Yield();
		var c = new Class();
		Assert.Throws<NullReferenceException>(async () => await c.Method());
	}
}

It fails only if Method returns Task < T >. If you change it to just Task it will work.

**Comment by picrap** [comment] 2016-10-19 08:01
I ran your test, and it throws the `NullReferenceException`, as expected...

**Comment by AlexanderButs** [comment] 2016-10-19 08:03
Are you sure you are using 2.0.20?

**Comment by picrap** [comment] 2016-10-19 08:03
😆 yes! The only changes I made were moving to MSTests.

**Comment by picrap** [comment] 2016-10-19 08:04
However I think I got your problem, I'm working on it.

**Comment by AlexanderButs** [comment] 2016-10-19 08:05
Also I build to 4.5 framework.

**Comment by picrap** [comment] 2016-10-19 08:06
Me too :) (these are the tests included in the solution)

**Comment by AlexanderButs** [comment] 2016-10-19 08:09
Also using NUnit 2.6.4 to create test. But using ReSharper runner to run it inside VS2012.

**Comment by picrap** [comment] 2016-10-19 08:56
2.0.21: let me know.

**Comment by AlexanderButs** [comment] 2016-10-19 08:59
unit test is ok (exception propagation issue). original issue will check a little bit later.

**Comment by AlexanderButs** [comment] 2016-10-24 08:27
Tried 2.1.0 on windows. Exception flow is broken again.

Error: [2016-10-24T11:14:48.690+03] 26 1022 - System.NullReferenceException: Object reference not set to an instance of an object.
   at ArxOne.MrAdvice.Invocation.GetResult(AdviceValues adviceValues)
   at ArxOne.MrAdvice.Invocation.<>c__DisplayClass2_0.<ProceedAdvice>b__1(Task t)
   at ArxOne.MrAdvice.Threading.TaskContinuer`1.<>c__DisplayClass0_0`1.<ContinueWith>b__0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DedicatedPoolServer.Repositories.CouchbaseDedicatedRepository.<GetAllAsync>d__0.MoveNext() in 

Will try 2.0.21 later.

**Comment by AlexanderButs** [comment] 2016-10-24 09:07
The same issue with 2.0.21. It doesn't even work. Throws when call async method with aspect.

**Comment by picrap** [comment] 2016-10-24 10:44
Does your exception come from advised method or advice itself?

**Comment by AlexanderButs** [comment] 2016-10-24 10:47
My method doesn't throw. It gets some data from db. So it comes from advise.

**Comment by picrap** [comment] 2016-10-24 10:49
But your advice does throw exception? Or no exception at all is thrown from your code? Because if your throw now exception and get an error, this is a bigger problem since all unit tests work.

**Comment by AlexanderButs** [comment] 2016-10-24 10:57
My code doesn't throw I think. I'll recheck this of course, but I think It doesn't. But even if my code throws your library shouldn't influence on that process.

**Comment by picrap** [comment] 2016-10-24 11:09
Absolutely, but that's not the same problem. If you can provide a small working sample that doesn't work, it would help a lot (a simple `.cs` file containing the advice and something failing is good enough).

**Comment by AlexanderButs** [comment] 2016-10-24 12:39
2.1.1 fixed runtime crashes (on win, haven't checked on linux), but unit tests are still red. Investigating.

**Comment by AlexanderButs** [comment] 2016-10-24 12:43
Advice:
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
	public class LogSuccessAsyncAttribute : Attribute, IMethodAsyncAdvice
	{
		public async Task Advise(MethodAsyncAdviceContext context)
		{
			await context.ProceedAsync();
			Console.WriteLine("Success!");
		}
	}

Method:
		[LogSuccessAsync]
		public Task<int> Method2(object p)
		{
			if (p == null)
			{
				throw new ArgumentNullException("p");
			}
			return Task.FromResult(0);
		}

Test:
		[Test]
		[ExpectedException(typeof(ArgumentNullException))]
		public async Task ShouldTest2()
		{
			var c = new Class();
			await c.Method2(null);
		}

Failed with:
An unexpected exception type was thrown
Expected: System.ArgumentNullException
 but was: System.NullReferenceException : Object reference not set to an instance of an object.
   at ArxOne.MrAdvice.Invocation.GetResult(AdviceValues adviceValues)
   at ArxOne.MrAdvice.Threading.TaskContinuer`1.<>c__DisplayClass0_0`1.<ContinueWith>b__0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TestFody.Test.Tests.<ShouldTest2>d__9.MoveNext() in Tests.cs: line 25
   at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()

**Comment by picrap** [comment] 2016-10-24 18:54
Thanks for test, I confirm it failed for me too and I fixed it in 2.1.2. Let me know, but everything should be fine now (at last!).

**Comment by AlexanderButs** [comment] 2016-10-25 08:47
Checked 2.1.2.
Unit tests are ok.
Exception flow is ok.
Original issue (with generics) is fixed.
But now seems to me aspect is created on every generic method call. With non-generic methods it works as earlier did. It shouldn't be like that, I think.

**Comment by picrap** [comment] 2016-10-25 09:15
Thanks for your patience 😉 
What do you mean by "aspect is created on every generic method call"? What type precisely?

**Comment by AlexanderButs** [comment] 2016-10-25 09:18
I mean aspect's ctor is invoked on each method call. I have a bool flag inside aspect for lazy initialization. And this flag is false every time generic method is invoked. I set it to true after first time my method is invoked.

**Comment by picrap** [comment] 2016-10-25 09:19
I'll take a look and eventually open an issue. Thanks for reporting it.

**Comment by AlexanderButs** [comment] 2016-10-25 09:33
Thanks for Your help. I think You can close this issue. But make sure You have all necessary tests to prevents these issues in the future.

**Comment by picrap** [comment] 2016-10-25 09:38
Yes, your sample is now included in the tests set 😉. Even if I make bugs, code quality and non-regression are my mantras.

**Comment by AlexanderButs** [comment] 2016-10-25 10:09
Cool. So create new issue with creating aspect on each generic method invocation. This issue is fixed.

**Comment by AlexanderButs** [comment] 2016-10-25 10:09
Also I can help you to test this in real proj.

**Comment by picrap** [comment] 2016-10-25 11:17
Good, because I didn't understand and reproduced your problem. Could you open a new issue with a code sample?
I close this one.

**Closed by picrap** 2016-10-25 11:17 UTC
Labels: bug

**Comment by AlexanderButs** [comment] 2016-10-25 12:13
Ok, I'll try to reproduce it and will come with workaround. Thanks.
