### ISSUE TITLE
add async support for the aspects

### ISSUE THREAD

**Issue by JonasSyrstad** [ArxOne/MrAdvice#52] opened 2016-01-05 19:35 UTC
Needed when doing exception handling and other aspects with post processing code.

**Comment by picrap** [comment] 2016-01-06 08:49
Could you tell me a bit more? Could you give me a small sample?

**Comment by JonasSyrstad** [comment] 2016-01-06 09:40
if you advice the method: public async Task DoStuffAsync() {//....} with:
Advice(MethodAdviceContext context)
{
//Some code run before the target
context.Proceed();
//some code to run after the target has completed
}
the code that should run after the target method is actually run before Proceed completes.

**Comment by picrap** [comment] 2016-01-06 10:55
Thank you, you're right. This is even more a bug than an enhancement :smile: I'm not sure to be available for this in the next few days, so you'll have to wait a bit (or submit a pull request?).

**Comment by JonasSyrstad** [comment] 2016-01-06 11:48
Thanx for the feedback.
we did a workaround outside of your code to get around this. But it would be nice to have built-in support for it. :)

**Comment by picrap** [comment] 2016-01-11 08:50
I just released a version 1.2 with support for async methods.
You have two ways to use it:
- If you don't make any change to your code it will work in a synchronous way (and this currently fully works).
- A new experimental `IAsyncMethodAdvice` interface but I need to fix an issue where post-proceed code in advice may be executed after await call has returned.
Let me know if the first option causes locks, I'm still working on the second option (which is going to be better, of course).

**Comment by picrap** [comment] 2016-01-11 16:10
Version 1.2.1 has a fully improved `IAsyncMethodAdvice` (which also works with non async methods, so you can unify your aspects).
Let me know if it's OK for you!

**Comment by JonasSyrstad** [comment] 2016-01-12 08:45
Great, thanx. 
I'll start testing the update now

**Comment by JonasSyrstad** [comment] 2016-01-13 12:24
Hi,
Seems like the fix you made are causing deadlocks in some scenarioes. task.Wait() runs the async operation on the same thread blocking it.

**Comment by picrap** [comment] 2016-01-13 12:26
Do you use `IMethodAdvice` or `IAsyncMethodAdvice`?

**Comment by JonasSyrstad** [comment] 2016-01-13 12:34
tried with both.

**Comment by picrap** [comment] 2016-01-13 12:37
In an `IAsyncMethodAdvice`, if you use `ProceedAsync()` instead of `Proceed()`, there won't be any `Task.Wait()` called. I know, I should document this... :wink:

**Comment by JonasSyrstad** [comment] 2016-01-13 12:44
didnt get that to work in my tests. I will send you a sample to show the problem.

**Comment by picrap** [comment] 2016-01-13 13:29
Yes, please. Also, what is your target platform? .NET 4.5? Silverlight? Other?

**Comment by JonasSyrstad** [comment] 2016-01-13 16:55
.net 4.5
I have done some more digging into the problem. looks like exceptions are lost in the new IAsyncMethodAdvice. If I do somehing like this in the advice:
using (var t = TracerFactory.StartTracer(context.TargetType, context.TargetMethod.Name))
            {
                if (info.ContainsCharacters()) t.SetAdidtionalInformation(info);
                try
                {
                    if (context.IsAwaitable() && !context.IsAsync()) context.ProceedAsync();
                    else if (context.IsAwaitable()) await context.ProceedAsync();
                    else context.ProceedAsync();
                }
                catch (AggregateException aex)
                {
                    if (aex == null || aex.InnerExceptions == null) throw;
                    if (aex.InnerExceptions.Count < 2) throw;
                    var ex = aex.InnerException;
                    if (TreatExceptionAsInformational) t.SetException(ex);
                    else t.SetErrorState(ex);
                    throw ex;
                }
                catch (Exception ex)
                {
                    if (TreatExceptionAsInformational) t.SetException(ex);
                    else t.SetErrorState(ex);
                    throw;
                }
            }

and add this to a method that throws an exception the exception is lost in synchronous methods and the application hangs for async.
Hope this helps :)

**Comment by picrap** [comment] 2016-01-13 17:36
You're right (once again!). I totally fogot the exceptions handling. Let's go!

**Comment by picrap** [comment] 2016-01-13 18:53
This should be fixed in version 1.2.3.

**Comment by JonasSyrstad** [comment] 2016-01-14 09:41
Hi,
Its getting better. still two issues though.
1: Task SomeMethod() is not handled correctly (Task<SomeT> SomeMethodOfT() works as expected )
2: synchronous methods are not wrapped correctly in the IAsyncMethodAdvice.

**Comment by picrap** [comment] 2016-01-14 10:09
Could you detail your point 1?

**Comment by albert-yang** [comment] 2016-01-14 11:43
Hi,

I just had a simple test for 1.2.3:

    [AttributeUsage(AttributeTargets.Method)]
    public class TestAsyncAttribute : Attribute, IAsyncMethodAdvice
    {
        public async Task Advise(AsyncMethodAdviceContext context)
        {
            Console.WriteLine("<==========before proceed==========>");
            await context.ProceedAsync();
            if (context.HasReturnValue)
            {
                Console.WriteLine(((dynamic)context.ReturnValue).Result);
                context.ReturnValue = Plus(((dynamic)context.ReturnValue).Result, 1);
                Console.WriteLine(((dynamic)context.ReturnValue).Result);
            }
            Console.WriteLine("<==========end proceed==========>");
        }

        private async Task<int> Plus(int i, int j)
        {
            return await Task.FromResult(i + j);
        }
    }

    class AsyncMethod
    {
        [TestAsync]
        public async Task<int> Foo()
        {
            await Task.Delay(3000);
            return 100;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var m = new AsyncMethod();
            InvokeAsync(m.Foo);
            Console.ReadLine();
        }

        static async void InvokeAsync<T>(Func<Task<T>> f)
        {
            var val = await f();
            Console.WriteLine(val);
        }
    }
and the result is 100 (expect 101).

I think the problem is in Invocation.ProceedAdvice:

            // if the method is no task, then we return immediately
            // (and the adviceTask is completed)
            var adviceTask = adviceContext.Invoke();
            var resultTask = adviceValues.ReturnValue as Task;
            // null adviceTask means aspect was sync, so everything already ended
            if (resultTask == null || adviceTask == null)
                return adviceValues.ReturnValue;

            // otherwise, see if it is a Task or Task<>

            // Task is simple too: the advised method is a subtask,
            // so the advice is completed after the method is completed too
            if (adviceValues.ReturnValue == typeof(Task))
                return adviceTask;

            // only Task<> left here
            // we need to create a new source and mark it as complete once the advice has completed
            var taskType = resultTask.GetTaskType();
            var adviceTaskSource = TaskCompletionSource.Create(taskType);
            adviceTask.ContinueWith(t => ContinueTask(t, adviceTaskSource, resultTask));
            return adviceTaskSource.Task;

You fetch the resultTask from adviceValues first, but actually you should re-fetch it when adviceTask is completed (to allow advice change the result somehow).

**Comment by picrap** [comment] 2016-01-16 17:57
The async problem is fixed (version 1.2.5), thanks for the sample.
However, I don't see any problem with an async advice advising a sync method.

**Comment by albert-yang** [comment] 2016-01-17 15:26
hi picrap,

Thanks for the quick fixing, the problem I mentioned has been fixed in version 1.2.5

However, I noticed there is similar problem with an async advice to be applied a sync method.

Please try following sample code:

    [AttributeUsage(AttributeTargets.Method)]
    public class TestAsyncAttribute : Attribute, IAsyncMethodAdvice
    {
        public async Task Advise(AsyncMethodAdviceContext context)
        {
            Console.WriteLine("<==========before proceed async==========>");
            await context.ProceedAsync();
            if (context.HasReturnValue)
            {
                if (context.ReturnValue is Task)
                {
                    Console.WriteLine(((dynamic) context.ReturnValue).Result);
                    context.ReturnValue = Plus(((dynamic) context.ReturnValue).Result, 1);
                    Console.WriteLine(((dynamic) context.ReturnValue).Result);
                }
                else
                {
                    Console.WriteLine(context.ReturnValue);
                    context.ReturnValue = (int)context.ReturnValue + 1;
                    Console.WriteLine(context.ReturnValue);
                }
            }
            Console.WriteLine("<==========end proceed async==========>");
        }

        private async Task<int> Plus(int i, int j)
        {
            return await Task.FromResult(i + j);
        }
    }

    class AsyncMethod
    {
        [TestAsync]
        public int Fooo()
        {
            Thread.Sleep(3000);
            return 1000;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var m = new AsyncMethod();
            var val = m.Fooo();
            Console.WriteLine("after call fooo: {0}", val);
            Console.ReadLine();
        }
    }

the function returns before async advice is finished.

**Comment by picrap** [comment] 2016-01-17 22:02
Fixed in 1.2.6.
However, this is something that shouldn't be done, since the async advice has to be waited for, hence, causing a deadlock if called from main thread.
I'll add a `IsAsync` property in the context, this will allow different processings in the advice. Or maybe add an advice with two methods one for sync targets, the other for async...

**Comment by albert-yang** [comment] 2016-01-18 02:32
Sounds great, currently we have to implement 2 version for an advice (one for sync, the other async), and they must be different classes, if we implement both IMethodAdvice and IAsyncMethodAdvice in one class, both of them will be executed which isn't our purpose. I think adding IsAsync property isn't much useful for us, cos there isn't an absolute safe way to call an async method from sync method, it might cause deadlock in some scenarios. so I suggest we should never mix  them, and just keep them in separated interfaces(what we have now). However we need to improve the weaving behavior to make sure it will automatically take the correct version. e.g. if I have an advice class which implemented both interfaces, I hope that the async version will be invoked for async method and vice versa. and further more to avoid mixing usage, if I apply an async only advice (only implement IAsyncMethodAdvice) to a sync method, I expect to get an error during compile time.

**Comment by picrap** [comment] 2016-01-18 09:51
Why not using a single async advice (`IAsyncMethodAdvice`) for both sync and async methods? The `context.ProceedAsync()` will work in both cases. Then, with an `IsAsync` property, you could perform extra asynchronous task.
I'm still thinking at what would be the best option, and on second thought, I don't like the idea of having and interface with two methods, one for sync methods, the other for async. This is not a unified way of working and I don't like it. This does not mean I won't do it, but I'm still thinking about it, that's all.

**Comment by picrap** [comment] 2016-01-20 22:10
I added an `IsTargetMethodAsync` property in the advices context (this is not released yet). So it all can be handled separately from within the same advice, whether it is an async advice or not.
I think that it's probably better this way.
The idea is that an advice extends the functionality of it targets in a uniform way, so it is probably a wrong way separating sync and async methods.

**Comment by Florismart** [comment] 2016-01-26 17:33
I am using 1.27 version of nuget and albert-yang problem does not seem solved. 
await inside async aspect does not really await.

**Comment by picrap** [comment] 2016-01-26 17:45
Could give me a sample of the problem (the advice, the method, and a method with what's expected)?

**Comment by Florismart** [comment] 2016-01-27 09:50
Hi Picrap, we are using Xamarin for a iOS and Droid project.
Solution is composed basically in a PCL for core, and a project for each platform. MrAdvice is installed in Droid and iOS projects.
So.. this is the snippet for Droid

###### Aspect (Droid):
```c#
[AttributeUsage (AttributeTargets.Method)]
public class ProgressWitnessAspect: Attribute, IAsyncMethodAdvice
{
	public async Task Advise (AsyncMethodAdviceContext context)
	{
		...
		activity.RunOnUiThread (() => {
			//Show Dialog
		});
		await context.ProceedAsync ();		//no await!
		activity.RunOnUiThread (() => {		//called immediatly
			//Dismiss Dialog
		});
	}
}
```

###### Fragment (Droid):
```c#
public class DetailFilmFragment : AVMDetailFragment<DetailViewModel>
{
		public override View OnCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
		{
			...
			Start();
			...
		}

		[ProgressWitnessAspect]
		private async void Start(){
			await ViewModel.StartAsync ();
		}
}
```

###### ViewModel (Pcl):
```c#
public class DetailViewModel: ADetailViewModel<DetailModel>
{

	public async override Task StartAsync ()
	{
		var response = await DetailService.Get (Id); 
		if (response != null) {
			...
		}
	}
}
```

###### Service (Pcl):
```c#
public class DetailService: IDetailService
{
	public async Task<DetailModel> Get (string id)
	{
		try {
			var response = await httpClient.GetStringAsync ("http://...");
			return JsonConvert.DeserializeObject<DetailModel> (response);
		} catch (Exception e) {
			e.ToString ();
		}
		return model;
	}
}
```

The problem is that the dialog is dismissed immediatly after been showed (no ProceedAsync awaited).

Many thanks!

**Comment by Florismart** [comment] 2016-01-27 16:28
I was going crazy.. We found the error!

```c#
[ProgressWitnessAspect]
private async void Start(){
      await ViewModel.StartAsync ();
}
```
**async vod** methods can not be awaited! 
*/facepalm*

###### Fixed with:

```c#
[ProgressWitnessAspect]
private async Task Start(){
      await ViewModel.StartAsync ();
}
```

Thanks! :+1:

**Comment by picrap** [comment] 2016-01-27 16:30
:laughing: I'm glad to help!
And I have read your sample several times without finding the error...

**Closed by picrap** 2016-01-27 16:30 UTC
Labels: bug
