### ISSUE TITLE
Fody error - using MrAdvice with methods with custom types parameters

### ISSUE THREAD

**Issue by rafallopatka** [ArxOne/MrAdvice#32] opened 2015-04-27 12:05 UTC
Hi,

I receive following error from fody during build (VS2013):

Error	1	Fody: An unhandled exception occurred:
Exception:
One or more errors occurred.
StackTrace:
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.Weave(ModuleDefinition moduleDefinition)
   at ModuleWeaver.Execute()
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
Source:
System.Core
TargetSite:
Void QueryEnd(Boolean)
opcode
StackTrace:
   at Mono.Cecil.Cil.Instruction.Create(OpCode opcode, Int32 value)
   at ArxOne.MrAdvice.Weaver.Instructions.EmitLdarg(Int32 index)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.WritePointcutBody(MethodDefinition method, MethodDefinition innerMethod)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveAdvices(MethodDefinition method)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass5.<Weave>b__0(MethodDefinition m)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.Cil.Instruction Create(Mono.Cecil.Cil.OpCode, Int32)
	Loggerv2

===========================================
Here is a sample code to recreate the issue. 

    public class Test
    {
        [MyProudAdvice] // this will pass
        public void Method1(FooClass fooClass)
        {
        }

        [MyProudAdvice] // this will pass
        public void Method1A(FooClass foo1, FooClass foo2)
        {
        }

        [MyProudAdvice] // fody error
        public void Method2(FooClass fooClass, string name, long id, long count)
        {
        }

        [MyProudAdvice] // fody error
        public void Method3(string name, FooClass fooClass, long id, long count)
        {
        }

        [MyProudAdvice] // fody error
        public void Method4(string name, long id, FooClass fooClass, long count)
        {
        }

        [MyProudAdvice] // fody error
        public void Method5(string name, long id, long count, FooClass fooClass)
        {
        }

        [MyProudAdvice] // fody error
        public void Method6(FooStruct fooStruct, string name, long id, long count)
        {
        }

        [MyProudAdvice] // fody error
        public void Method6(FooEnum fooEnum, string name, long id, long count)
        {
        }
    }

    public enum FooEnum
    {
        
    }

    public struct FooStruct
    {
        public int Id { get; set; }
    }

    public class FooClass
    {
        public int Id { get; set; }
    }

    public class MyProudAdvice : Attribute, IMethodAdvice
    {
        public void Advise(MethodAdviceContext context)
        {
            // do things you want here
            context.Proceed(); // this calls the original method
            // do other things here
        }
    }

**Comment by picrap** [comment] 2015-04-27 15:02
Fixed in 0.9.5. This was caused by incorrect handling of method with 4 or more parameters.
Thanks for pointing it out!

**Closed by picrap** 2015-04-27 15:02 UTC
Labels: bug

**Comment by rafallopatka** [comment] 2015-04-27 16:37
Thanks a lot

**Comment by picrap** [comment] 2015-04-27 17:04
You're welcome! All suggestions for the product are also welcome :wink:
