### ISSUE TITLE
Exception handling inside the Advice

### ISSUE THREAD

**Issue by sadra-ab** [ArxOne/MrAdvice#101] opened 2017-03-23 16:58 UTC
Hello,
and thanks for the awesome work!

I am facing a problem when handling exceptions in my advice. Here's what I'm doing:

	public class MyMethodAdviceAttribute : Attribute, IMethodAsyncAdvice
	{
		public async Task Advise(MethodAsyncAdviceContext context)
		{
			try
			{
				if (context.IsTargetMethodAsync)
					await context.ProceedAsync();
				else
					Task.Run(context.ProceedAsync).Wait();
			}
			catch (Exception ex)
			{
				var myLocalVar = ex;
			}
		}
	}

and I use it as:

	[MyMethodAdvice]
	public string SayHello()
	{
		throw new Exception("From SayHello");
	}

	[MyMethodAdvice]
	public Task<string> SayHelloAsync()
	{
		throw new Exception("From SayHelloAsync");
	}

The problem I am facing is that when I inspect the variable "ex" (of type Exception), I get "The name 'ex' does not exist in the current context". This happens regardless if the method is async or not. 

I also tried to wrap the caller in a try-catch block, and still facing the same problem

	try
	{
		myService.SayHello();
		await myService.SayHelloAsync();
	}
	catch (Exception ex)
	{
		var myLocalVar = ex;
	}

I also tried throwing a new exception (following your unit test method "AsyncExceptionTranslationAdvice" in "AsyncTest"), but still no lock.

Any help will be greatly appreciated.

**Comment by picrap** [comment] 2017-03-23 17:11
Hi,

You won't like my answer (I don't like it neither), but this is related to the code generation library we're using, named dnlib, which does not support async in PDB right now.
The issue is here: https://github.com/0xd4d/dnlib/issues/94
So currently, debug info works well in methods that are not marked `async`. If you absolutely need to watch your exception, simply wrap your code in a non-async method and you will be able to see it from that method.
I am really sorry about this, and I'm also waiting for this problem to be fixed.

**Comment by sadra-ab** [comment] 2017-03-23 17:21
Thanks for the quick response.

So, the reason why I need to get a handle to the exception is to log it. What you saying means that I can go ahead, and log my exception, and it should just work, right?

And yes, I tried it and it did.

Thanks again.

**Comment by picrap** [comment] 2017-03-23 17:23
Yes absolutely. It's just a part of the PDB which is missing after MrAdvice on `async` methods. The code fully works.

**Comment by picrap** [comment] 2017-03-24 22:20
Related to #91, so I'm closing this one.

**Closed by picrap** 2017-03-24 22:20 UTC
Labels: bug, on hold
