### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Florismart** [ArxOne/MrAdvice#94] opened 2017-03-09 10:35 UTC
Hi,
last year I used MrAdvice.Fody (v 1.2.7) in a Xamarin Project (iOS and Droid both) without problems.
I just started another project (with a PCL and an iOS projects) and I noticed that MrAdvice.Fody is deprecated. (C# 4.5)
So, I tried include new suggested nuget MrAdvice.

In iOS project Xamarin Studio correctly added Package and Reference but, at compile time, I have this problem:

`/Users/MyUser/Documents/git_xamarin/MyProject/packages/MrAdvice.2.4.5/build/MrAdvice.targets: Error: Internal error: System.IO.FileNotFoundException: Could not load file or assembly 'MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8' or one of its dependencies
File name: 'MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8'
  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly) [0x0003d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.AppDomain.Load (System.String assemblyString) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)
  at System.Reflection.Assembly.Load (System.String assemblyString) [0x00005] in <8f2c484307284b51944a1a13a14c0266>:0 
  at ArxOne.MrAdvice.MrAdviceStitcher.Process (StitcherBoy.Weaving.Build.AssemblyStitcherContext context) [0x000e6] in <24a35298ea264200b2cfa6723955cb10>:0  (MyProject.iOS)`

![schermata 2017-03-09 alle 11 46 44](https://cloud.githubusercontent.com/assets/2580528/23747744/13ee3c86-04c1-11e7-877d-b32220d38aa5.png)

I tried rename "net40-client" folder into net45-client" for test and Error disappeared but aspect doesn't work. 

Any ideas?
Many Thanks

**Comment by picrap** [comment] 2017-03-09 18:45
Hi,

I'm sorry to read this. I don't understand why it requires the assembly in a net45 folder, since the assembly targets .Net 4.0. Apparently the weaver is invoked, so I don't understand why the assembly is not weaved.
I'll need to install Xamarin Studio and see it myself.

**Comment by picrap** [comment] 2017-03-09 18:46
... Unfortunately, Xamarin Studio is not supported anymore. Can you give it a try with Visual Studio for Mac?

**Comment by picrap** [comment] 2017-03-10 09:29
Good to see you have an alternative. I'll try to download Xamarin Studio from somewhere (but where?) and see if I can reproduce the problem.

**Comment by Florismart** [comment] 2017-03-10 09:37
Xamarin Studio is now completly free and you can download it from: [Xamarin Site](https://www.xamarin.com/download-it)

Many thanks @picrap !

**Comment by picrap** [comment] 2017-03-10 20:48
Xamarin Studio is not available anymore on Windows, but Xamarin support is present in Visual Studio. Could eventually provide a simple project that has the problem?

**Comment by emmanuele-villa** [comment] 2017-05-16 09:48
Hi! I also have a similar problem with Fody: I tried with Visual Studio for Mac but I have an error in the MrAdvice.targets at the line 
`<MrAdviceTask AssemblyPath="@(IntermediateAssembly)" ReferencePath="@(ReferencePath)" ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"`
The error is: 
/Projects/FodyFody/packages/MrAdvice.2.5.0/build/MrAdvice.targets(5,5): Error: Unhandled exception: System.DllNotFoundException: ole32

**Comment by picrap** [comment] 2017-05-16 12:59
Huh? I need to find what references ole32, a native Windows DLL, from a .NET assembly... But it's probably not Mr Advice...

**Comment by emmanuele-villa** [comment] 2017-05-16 13:02
Yes, that's really strange.. I only have Mr. Advice in the packages, it's an empty solution that I made to check if it works with the new visual studio for mac.. let me know if I can help you in some way! Thanks

**Comment by picrap** [comment] 2017-05-16 13:29
OK, I found it (this is in another project, named StitcherBoy). Not sure I will be able to fix it, but I'll take a look.

**Comment by emmanuele-villa** [comment] 2017-07-24 17:02
Any news on this? :)

**Comment by picrap** [comment] 2017-07-24 17:07
Sorry, I didn't work on it all (shame). I'll work on it this week.

**Comment by emmanuele-villa** [comment] 2017-07-26 07:16
No problem :)
An update:
with the latest Visual Studio for Mac update I have another error (not sure if it comes before the ole32 one, or that is disappeared)

`
/Users/emmanuele.villa/Projects/MrAdviceTest/packages/MrAdvice.2.5.4/build/MrAdvice.targets(5,5): Error: Unhandled exception: System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'dnlib.DotNet.Pdb.Managed.PdbException' was not found. ---> System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'dnlib.DotNet.Pdb.Managed.PdbException' was not found.
  at System.Runtime.Serialization.ObjectManager.GetConstructor (System.RuntimeType t) [0x0002f] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/objectmanager.cs:891 
  at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject (System.Object obj, System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) [0x00034] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/objectmanager.cs:867 
   --- End of inner exception stack trace ---
  at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject (System.Object obj, System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) [0x0003e] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/objectmanager.cs:871 
  at System.Runtime.Serialization.ObjectManager.FixupSpecialObject (System.Runtime.Serialization.ObjectHolder holder) [0x0007b] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/objectmanager.cs:259 
  at System.Runtime.Serialization.ObjectManager.DoFixups () [0x0005a] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/objectmanager.cs:925 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00077] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryobjectreader.cs:181 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00099] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:197 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00000] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:173 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck) [0x00000] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:118 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) [0x00000] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:149 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) [0x00000] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:111 
  at System.Runtime.Remoting.RemotingServices.DeserializeCallData (System.Byte[] array) [0x0000c] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/corlib/System.Runtime.Remoting/RemotingServices.cs:794 
  at (wrapper xdomain-invoke) StitcherBoy.Weaving.StitcherProcessor:Process (System.Collections.Specialized.StringDictionary,System.Guid,System.DateTime,string)
  at (wrapper remoting-invoke-with-check) StitcherBoy.Weaving.StitcherProcessor:Process (System.Collections.Specialized.StringDictionary,System.Guid,System.DateTime,string)
  at StitcherTask1[TSingleStitcher].Run (System.Boolean fromExe) [0x00157] in <3b70d110029b4408a3137d36524355b8>:0  (MrAdviceTest)
`

This is my configuration:
Visual Studio Community 2017 for Mac, version 7.0.1 (build 24)
Mono 5.0.1.1
GTK+ 2.24.23
Xcode: 8.3.3
Xamarin.iOS: 10.10.0.36

If you have some hint of what I could check in the meantime, I'll be glad to help you find the problem!

thanks

**Comment by picrap** [comment] 2017-07-26 07:47
This one comes from the PDB format change (there is a new PDB format named `portable`), so if you set back your PDB format to an old one (`database` or `full`), the exception should disappear.
The library used by MrAdvice, named `dnlib` does not support the `portable` format.

**Comment by emmanuele-villa** [comment] 2017-07-26 07:50
Thanks! I'll tell this to the MrAdvice guy :)

**Comment by emmanuele-villa** [comment] 2017-07-26 07:52
Sorry, I didn't understand the point. How can I change the pdb format if the library is used by MrAdvice? Shouldn't you change it inside it? I have an empty test project, so only MrAdvice is referenced

**Comment by picrap** [comment] 2017-07-26 07:58
This is the pdb format from the library you want to advice, i.e. your library. So you just need to change the format somewhere in the project properties.

**Comment by emmanuele-villa** [comment] 2017-07-26 08:09
I found about that problem on xamarin where you use an unsupported pdb format [here](https://forums.xamarin.com/discussion/91001/vs-2017-error-convertpdbtomdb-task-failed-unexpectedly-portablepdbnotsupportedexception), but after changing the DebugType to "full" as stated [here](https://developer.xamarin.com/guides/android/under_the_hood/build_process/#Build_Properties), the error doesn't change..
The same error happens in release mode, so how is it related to the debug modes?
Maybe we are talking about two different things with the same name? The only pdb reference that I found in xamarin projects is that one..

**Comment by picrap** [comment] 2017-07-28 08:13
Just to keep you informed: there have been some updates in dnlib which cause trouble somewhere in MrAdvice build, so I'll need more time than expected.

**Comment by emmanuele-villa** [comment] 2017-07-28 08:33
ok! thanks for the work :)

**Comment by picrap** [comment] 2017-08-05 21:48
It's great to be back (as the dead guy said)!
Can you try the version 2.5.5 (this is a blind fix, so I'm sure it will work)?

**Comment by emmanuele-villa** [comment] 2017-08-07 08:27
I tried version 2.5.9, the latest that I see in the nuget manager.
An error is still present on that line, but it changed! So I guess it's a step in the right direction

`/Users/emmanuele.villa/Projects/MrAdviceTest/packages/MrAdvice.2.5.9/build/MrAdvice.targets(5,5): Error: Unhandled exception: dnlib.DotNet.Pdb.Managed.PdbException: Failed to read PDB: Invalid signature Server stack trace: at dnlib.DotNet.Pdb.Managed.PdbReader.ReadInternal (dnlib.IO.IImageStream stream) [0x00033] in <56f00b436f61465791ccd65abd08f147>:0 at dnlib.DotNet.Pdb.Managed.PdbReader.Read (dnlib.IO.IImageStream stream) [0x00007] in <56f00b436f61465791ccd65abd08f147>:0 at dnlib.DotNet.Pdb.Managed.SymbolReaderCreator.Create (dnlib.IO.IImageStream pdbStream) [0x0000e] in <56f00b436f61465791ccd65abd08f147>:0 at dnlib.DotNet.Pdb.Managed.SymbolReaderCreator.Create (System.Byte[] pdbData) [0x00006] in <56f00b436f61465791ccd65abd08f147>:0 at dnlib.DotNet.Pdb.SymbolReaderCreator.Create (dnlib.DotNet.Pdb.PdbImplType pdbImpl, dnlib.DotNet.MD.IMetaData metaData, System.Byte[] pdbData) [0x0001a] in <56f00b436f61465791ccd65abd08f147>:0 at dnlib.DotNet.ModuleDefMD.LoadPdb (dnlib.DotNet.Pdb.PdbImplType pdbImpl, System.Byte[] pdbData) [0x00000] in <56f00b436f61465791ccd65abd08f147>:0 at StitcherBoy.Reflection.ModuleManager..ctor (System.String assemblyPath, System.Boolean usePdb, System.Nullable'1[T] useTemp) [0x0006c] in <56f00b436f61465791ccd65abd08f147>:0 at StitcherBoy.Weaving.Build.AssemblyStitcher.LoadModule (System.String assemblyPath) [0x00015] in <56f00b436f61465791ccd65abd08f147>:0 at StitcherBoy.Weaving.Build.AssemblyStitcher.Process (System.Collections.Specialized.StringDictionary parameters, System.Guid buildID, System.DateTime buildTime, System.String entryAssemblyPath) [0x0006c] in <56f00b436f61465791ccd65abd08f147>:0 at StitcherBoy.Weaving.StitcherProcessor.Process (System.Collections.Specialized.StringDictionary parameters, System.Guid buildID, System.DateTime buildTime, System.String entryAsemblyPath) [0x0001c] in <56f00b436f61465791ccd65abd08f147>:0 at (wrapper remoting-invoke-with-check) StitcherBoy.Weaving.StitcherProcessor:Process (System.Collections.Specialized.StringDictionary,System.Guid,System.DateTime,string) at (wrapper xdomain-dispatch) StitcherBoy.Weaving.StitcherProcessor:Process (object,byte[]&,byte[]&,string) Exception rethrown at [0]: at (wrapper xdomain-invoke) StitcherBoy.Weaving.StitcherProcessor:Process (System.Collections.Specialized.StringDictionary,System.Guid,System.DateTime,string) at (wrapper remoting-invoke-with-check) StitcherBoy.Weaving.StitcherProcessor:Process (System.Collections.Specialized.StringDictionary,System.Guid,System.DateTime,string) at StitcherTask'1[TSingleStitcher].Run (System.Boolean fromExe) [0x00157] in <56f00b436f61465791ccd65abd08f147>:0 (MrAdviceTest.iOS)`

**Comment by picrap** [comment] 2017-08-07 08:29
Sure it is! Try to generate something else than `portable` format as debug info, since dnlib (used by Mr Advice) does not support it.

**Comment by emmanuele-villa** [comment] 2017-08-07 09:47
I tried both debug info that are compatible with xamarin with no luck:
`<DebugType>pdbonly</DebugType>`
and
`<DebugType>full</DebugType>`
Unfortunately the same error is still there..

Looking at the lib stacktrace, the exception is raised [here](https://github.com/0xd4d/dnlib/blob/289b5048228fb40f807490060be2bc2caf193449/src/DotNet/Pdb/Managed/PdbReader.cs), line 68:
```
if (sig != "Microsoft C/C++ MSF 7.00\r\n\u001ADS\0")
	throw new PdbException("Invalid signature");
```

**Comment by picrap** [comment] 2017-08-07 09:49
What signature do you have in your pdb? There are the first 32 bytes of the file.

**Comment by emmanuele-villa** [comment] 2017-08-07 10:19
The signature is
`42534A42 01000100 00000000 0C000000 50444220 76312E30 00000000 00000600`
which should be "BSJB PDB v1.0".
I can see the "Microsoft C/C++ MSF 7.00\r\n\u001ADS\0" correct signature in the build done on my other windows machine

**Comment by picrap** [comment] 2017-08-07 11:27
I released a version 2.5.10 which bypasses PDB header check. Can you tell me if it works with any of the PDB formats?

**Comment by emmanuele-villa** [comment] 2017-08-07 12:15
Unfortunately, in Debug it blocks at the next check, at line 79 with "File size mismatch", both with "full" and "pdbobly"

But if I build in release, the build is successfull with a warning:
`/Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. (MSB3276) (MrAdviceTest.iOS)`
and the advice works! :D

Maybe you could try to disable also the file size check? Even if it doesn't sounds so easy as the header one..

**Comment by picrap** [comment] 2017-08-07 19:00
That won't be possible, the data don't match after header, unfortunately. I'll make a request to dnlib to handle this format. However I'm not sure with will happen soon.

**Comment by emmanuele-villa** [comment] 2017-08-08 06:48
Ok! Thanks a lot for now, can't wait for news about it! :)

**Comment by picrap** [comment] 2017-08-08 06:51
Don't forget to upvote https://github.com/0xd4d/dnlib/issues/128 👍

**Comment by emmanuele-villa** [comment] 2017-08-08 07:01
sure! :)
I don't want to make you do a lesson about how mr advice works, but why in release mode it works just by skipping the header check? Doing that thing in debug mode is a way to make mr advice debuggable?

**Comment by picrap** [comment] 2017-08-08 07:52
I have no idea! I guess that in release mode, the PDB file is empty or non existing.

**Comment by picrap** [comment] 2017-11-08 21:59
@emmanuele-villa I just released a 2.5.18-pre (a preversion). Can you test it with portable PDB files?

**Comment by emmanuele-villa** [comment] 2017-11-10 10:56
Hi! I tried, but I'm not sure that the new dnlib library kicked in:
`packages/MrAdvice.2.5.18-pre/build/MrAdvice.targets(5,5): Error: Debug info is using portable format which is unsupported now. Please upvote the issue at https://github.com/0xd4d/dnlib/issues/128`

**Comment by picrap** [comment] 2017-11-10 11:24
I totally suck! I'll fix this today. Sorry.

**Comment by picrap** [comment] 2017-11-11 12:05
2.5.18-pre2... Let me know!

**Comment by emmanuele-villa** [comment] 2017-11-11 18:06
Good news: the error went away!
Bad news: there is another error :D

It's not a compile time, but it's a build error (just in debug, in release it still works!):
```
/Users/willyrs/Projects/mradvicetest/iOS/bin/iPhoneSimulator/Debug/mradvicetest.iOS.exe -v -v 
    MTOUCH : error MT0009: Error while loading assemblies: /Users/willyrs/Projects/mradvicetest/iOS/bin/iPhoneSimulator/Debug/mradvicetest.iOS.exe
    	Non-negative number required.
    Parameter name: count
Done building target "_CompileToNative" in project "mradvicetest.iOS.csproj" -- FAILED.
```

On android it's the same, but I'm reporting also the android error because it has a different syntax and maybe that helps understand the issue better:
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error: Exception while loading assemblies: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA0009: Error while loading assembly: bin/Debug/mradvicetest.dll ---> System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
  at System.IO.BinaryReader.ReadBytes (System.Int32 count) [0x00071] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/binaryreader.cs:558 
  at Mono.Cecil.PE.ImageReader.ReadDebugHeader () [0x000f7] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil.PE/ImageReader.cs:351 
  at Mono.Cecil.PE.ImageReader.ReadImage () [0x000a8] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil.PE/ImageReader.cs:89 
  at Mono.Cecil.PE.ImageReader.ReadImage (Mono.Disposable`1[T] stream, System.String file_name) [0x00007] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil.PE/ImageReader.cs:753 
  at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00006] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/ModuleDefinition.cs:1136 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006c] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/ModuleDefinition.cs:1108 
  at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00000] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/AssemblyDefinition.cs:134 
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly (System.String file) [0x00129] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:149 
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load (System.String fileName) [0x00024] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:115 
   --- End of inner exception stack trace ---
  at Java.Interop.Tools.Diagnostics.Diagnostic.Error (System.Int32 code, System.Exception innerException, System.String message, System.Object[] args) [0x00000] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs:163 
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load (System.String fileName) [0x0002f] in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:117 
  at Xamarin.Android.Tasks.ResolveAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x00111] in <593a6fd557984367bb21e275d0fa0659>:0  (mradvicetest.droid)
```
Thanks a lot for your support :)

**Comment by picrap** [comment] 2017-11-11 23:40
I also had problems between `dnlib` (used by Mr. Advice) and `Cecil`.
I'll see with `dnlib`'s author if something can be done.

**Comment by picrap** [comment] 2018-10-23 15:47
@PankajRawat333: I don't think this is related to your problem. Please open another issue with a bit more explanations.

**Comment by PankajRawat333** [comment] 2018-10-23 16:22
@picrap  Thanks for reply, I will provide complete detail

**Comment by TonyC5** [comment] 2018-11-06 22:30
@picrap and @PankajRawat333 - I'm trying to use dnlib with ConfuserEx (to obfuscate Xamarin.Forms PCL dlls) on MacOS (High Sierra 10.13.6) and I am seeing 

    Exception: dnlib.DotNet.Pdb.Managed.PdbException: Failed to read PDB: Invalid signature

I don't know enough to determine whether my error is related to this thread.  How can I get your version of dnlib to try in my environment?  Thank you.

**Comment by picrap** [comment] 2018-11-07 07:38
Hi @TonyC5, my version of dnlib has nothing special, it is usually the latest version from the official repo.

**Comment by picrap** [comment] 2021-04-26 19:36
Hi everyone here, there has been a major rewrite of Mr Advice weaver, and I would like to close this issue, if no one is against.

**Closed** 2021-09-17 20:33 UTC
Labels: bug, to be closed
